### ISSUE TITLE
Session#close may crash on Zlib#close

### ISSUE THREAD

**Issue by Slayer95** [faye/permessage-deflate-node#5]
Stack as follows:

```
TypeError: Cannot read property 'close' of null
    at InflateRaw.Zlib.close (zlib.js:466:15)
    at Session.close (/srv/node_modules/permessage-deflate/lib/session.js:117:59)
    at Cell._doClose (/srv/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/cell.js:47:36)
    at Cell.close (/srv/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/cell.js:30:8)
    at /srv/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:24:55
    at Array.map (native)
    at Pipeline.close (/srv/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:24:28)
    at instance.close (/srv/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:142:20)
    at instance._shutdown (/srv/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:299:22)
```

Node v. 4.2.1, running a `SockJS` server in Ubuntu 14.04.3

`this._handle` is `null` here https://github.com/nodejs/node/blob/b7eff480d8fbeb0576bb98ca771fb1ad6f48e864/lib/zlib.js#L466

Which apparently happens if there was an error in the compression: https://github.com/nodejs/node/blob/b7eff480d8fbeb0576bb98ca771fb1ad6f48e864/lib/zlib.js#L357-L360

**Comment by jcoglan** [comment]
This should be fixed in https://github.com/faye/permessage-deflate-node/commit/d22edec9962d95cfebd4b2e2116f91a3fafbc247. Can you let me know if that works for you and close the issue if so?

**Comment by Slayer95** [comment]
Thanks! I am afraid I don't have a reliable test case in my app, so I'll close if I don't see it crash in a while.

**Comment by Slayer95** [comment]
No news is good news! I'm closing :)
